workflows:
  android-debug:
    name: PoM Android Debug APK
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
      vars:
        FIREBASE_APP_ID: "1:1049001087254:android:6c7969c2a9746c378b4037"
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - mobile/.dart_tool
        - mobile/build/app/outputs
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        working_directory: mobile
      - name: Build debug APK
        script: |
          flutter build apk --debug \
            --no-tree-shake-icons \
            --suppress-analytics
        working_directory: mobile
    artifacts:
      - mobile/build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_APP_ID
          groups:
            - testers
      email:
        recipients:
          - ozkanmuhammed8060@gmail.com
        notify:
          success: true
          failure: true
